[program:zy4panel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/zy4hosting/panel/artisan queue:work redis --sleep=3 --tries=3 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/zy4hosting/panel/storage/logs/worker.log
stopwaitsecs=3600
